const sentences = [
    "A friend in need is a friend indeed",
    "Actions speak louder than words",
    "A journey of a thousand miles begins with a single step",
    "A picture is worth a thousand words",
    "Better late than never",
    "Birds of a feather flock together",
    "Dont judge a book by its cover",
    "Easy come easy go",
    "Every cloud has a silver lining",
    "Honesty is the best policy",
    "If it aint broke dont fix it",
    "Knowledge is power",
    "Laughter is the best medicine",
    "No pain no gain",
    "Practice makes perfect",
    "The early bird catches the worm",
    "Time is money",
    "Two heads are better than one",
    "When in Rome do as the Romans do",
    "Where theres a will theres a way",
    "You cant judge a book by its cover",
    "You cant make an omelette without breaking eggs",
    "You reap what you sow",
    "The pen is mightier than the sword",
    "Too many cooks spoil the broth",
    "Many hands make light work",
    "A stitch in time saves nine",
    "The grass is always greener on the other side",
    "A rolling stone gathers no moss",
    "Fortune favors the bold",
    "All that glitters is not gold",
    "Beauty is in the eye of the beholder",
    "Better safe than sorry",
    "Brevity is the soul of wit",
    "Cleanliness is next to godliness",
    "Discretion is the better part of valor",
    "Familiarity breeds contempt",
    "Good things come to those who wait",
    "Great minds think alike",
    "Haste makes waste",
    "He who laughs last laughs best",
    "History repeats itself",
    "If at first you dont succeed try try again",
    "Ignorance is bliss",
    "Imitation is the sincerest form of flattery",
    "It takes two to tango",
    "Jack of all trades master of none",
    "Keep your friends close and your enemies closer",
    "Let sleeping dogs lie",
    "Look before you leap"
];


